- name: Playbook to provision a VM on VMware
  hosts: localhost
  gather_facts: false

  tasks:
   - name: set connection info
      ansible.builtin.set_fact:
        connection_args:
          vcenter_hostname: ""
          vcenter_username: ""
          vcenter_password: ""
          vcenter_validate_certs: "false"

    - name: Test urlEncoded issue with list datasoruces
      vmware.vmware_rest.vcenter_datacenter_info:
        vcenter_hostname: "{{ connection_args.vcenter_hostname }}"
        vcenter_username: "{{ connection_args.vcenter_username }}"
        vcenter_password: "{{ connection_args.vcenter_password }}"
        vcenter_validate_certs: "false"
      register: create_vsphere_vm_datacenter
