- name: License info
  ansible.builtin.include_tasks: license_info.yml
  when: info_license
  tags:
    - license

- name: Appliance info
  ansible.builtin.include_tasks: appliance_info.yml
  when: info_appliance
  tags:
    - appliance

- name: Guest info
  ansible.builtin.include_tasks: guest_info.yml
  when: info_guest
  tags:
    - guest

- name: Cluster info
  ansible.builtin.include_tasks: cluster_info.yml
  when: info_cluster
  tags:
    - cluster

- name: Storage info
  ansible.builtin.include_tasks: storage_info.yml
  when: info_storage
  tags:
    - storage

- name: Expose Gathered Facts As Variable vmware_ops_info_outputs
  ansible.builtin.set_fact:
    vmware_ops_info_outputs:
      license: "{{ __license.licenses | first | default({}) }}"
      appliance: "{{ __appliance.appliance | default({}) }}"
      guest: "{{ __guests.guests | first | default({}) }}"
      cluster: "{{ __clusters_info.results | map(attribute='clusters') | default({}) }}"
      storage: "{{ __storage_policy.spbm_profiles | first | default({}) }}"
  when: info_expose_outputs_as_variable
