---
- name: Gather Required OS Facts
  ansible.builtin.setup:
    gather_subset:
      - system
  when: ansible_os_family is not defined

- name: Template Installer Config JSON
  ansible.builtin.template:
    src: vcsa_deployment_config.json.j2
    dest: /tmp/vcsa_deployment_config.json
    mode: "0600"

- name: Install from ISO
  block:
    - name: Mount vCSA ISO as Read-Only
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - mount_{{ ansible_os_family }}.yml
            - mount_default.yml
          paths:
            - os_specific_iso_actions
    - name: Deploy vCSA With Local Log Written To /tmp/vcsa.log
      ansible.builtin.shell: >-
        ./vcsa-deploy install -v --accept-eula --no-ssl-certificate-verification
        --acknowledge-ceip /tmp/vcsa_deployment_config.json > /tmp/vcsa.log 2>&1
      args:
        chdir: "{{ provision_vcenter_iso_mount_point }}/vcsa-cli-installer/lin64"
  always:
    - name: Remove The Installer Config JSON
      ansible.builtin.file:
        path: /tmp/vcsa_deployment_config.json
        state: absent
    - name: Unmount vCSA ISO
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - unmount_{{ ansible_os_family }}.yml
            - unmount_default.yml
          paths:
            - os_specific_iso_actions
